backend:
  name: github
  repo: khuevan/personal-blog-qlda

media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/posts
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: subTitle, label: SubTitle }
      - { name: category, label: Category }
      - { name: body, label: Body, widget: markdown }
      