backend:
  name: github
  repo: khuevan/personal-blog-qlda

media_folder: ''
public_folder: ''

collections:
  - name: blog
    label: Blog
    folder: content/posts
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{year}}/{{month}}/{{day}}--{{title}}/index'
    create: true
    fields:
      - { name: title, label: Title }
      - { name: subTitle, label: SubTitle }
      - { name: category, label: Category required: false }
      - { name: cover, label: Cover Image, widget: image, required: false, tagname: ""}
      - { name: body, label: Body, widget: markdown }
      