backend:
  name: github
  repo: khuevan/personal-blog-qlda

media_folder: content/assets
public_folder: ../assets

collections:
  - name: bloga
    label: Blog
    folder: content/posts/*
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
