backend:
  name: github
  repo: khuevan/personal-blog-qlda

media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/posts
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: subTitle, label: SubTitle }
      - { name: category, label: Category }
      - { name: image, label: Cover Image, widget: image, required: false, tagname: ""}
      - { name: body, label: Body, widget: markdown }
      